config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  concern :voted do
    member do
      patch :vote_up
      patch :vote_down
      delete :revoke_vote
    end
  end

  concern :commented do
    post :comment, on: :member
  end

  resources :questions, concerns: %i[voted commented] do
    resources :answers, concerns: %i[voted commented], shallow: true, except: :index do
      patch :set_best, on: :member
    end
  end

  resources :questions, concerns: :voted do
    post :subscribe, on: :member
    post :unsubscribe, on: :member
    delete :delete_attachment, on: :member
    delete :delete_attachment_for_answer, on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [] do
        get :me, on: :collection
        get :exept_me, on: :collection
      end
      resources :questions do
        resources :answers
      end
    end
  end

  get 'search', to: 'search#search'

  root to: 'questions#index'
  mount ActionCable.server => '/cable'
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :bigint           not null, primary key
#  body       :text
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint
#
# Indexes
#
#  index_questions_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Question < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :user, touch: true
  has_many :answers, dependent: :destroy
  has_many :attachments, as: :attachable, inverse_of: :attachable
  has_many :subscribe_lists, dependent: :destroy
  has_many :subscribers, class_name: 'User', through: :subscribe_lists

  scope :created_yesterday, -> { where(created_at: Time.zone.now.yesterday.all_day) }

  after_create :subscribe_author

  validates :title, presence: true
  validates :body, presence: true

  accepts_nested_attributes_for :attachments, allow_destroy: true

  def subscribe(user)
    self.subscribers << user unless has_subscribed? user
  end

  def unsubscribe(user)
    self.subscribers.delete(user) if has_subscribed? user
  end

  def has_subscribed?(user)
    subscribers.include? user
  end

  private

  def subscribe_author
    subscribe(user)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController< Api::V1::BaseController
  before_action :load_question, only: [:show]
  respond_to :json

  def index
  	@questions = Question.all
  	respond_with @questions
  end

  def show
    respond_with @question
  end

  def create
    @question = Question.new(questions_params)
    @question.user_id = current_resource_owner.id
    respond_with @question if @question.save
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def questions_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_question, only: %i[show destroy update delete_attachment subscribe unsubscribe]
  after_action :publish_question, only: :create

  include Voted
  include Commented

  def index
    @questions = Question.all
  end

  def show
    @answer = Answer.new(question: @question)
    @answer.attachments.build
  end

  def new
    @question = Question.new
    @question.attachments.build
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    if @question.save
      redirect_to question_path(@question)
      flash[:notice] = 'Your question successfully created.'
    else
      render :new
    end
  end

  def destroy
    if current_user.author?(@question)
      flash[:notice] = 'Your question has been successfully deleted!' if @question.destroy
    else
      flash[:notice] = 'You are not able to delete this question!'
    end

    redirect_to questions_path
  end

  def update
    @question.update(question_params)
  end

  def delete_attachment
    @attachment = @question.attachments.find(params[:attach_id])
    @attachment.destroy
    render :delete_attachments
  end

  def delete_attachment_for_answer
    @answer = Answer.find(params[:id])
    @attachment = @answer.attachments.find(params[:attachment_id])
    @attachment.destroy
    render :delete_attachments
  end

  def subscribe
    @question.subscribe(current_user)
    redirect_to @question, notice: 'Subscribed successfully!'
  end

  def unsubscribe
    @question.unsubscribe(current_user)
    redirect_to @question, notice: 'Unsubscribed successfully!'
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: %i[id file _destroy])
  end

  def load_question
    @question = Question.find(params[:id])
  end

  def publish_question
    return if @question.errors.any?

    ApplicationController.renderer.instance_variable_set(
      :@env, {
        'HTTP_HOST' => 'localhost:3000',
        'HTTPS' => 'off',
        'REQUEST_METHOD' => 'GET',
        'SCRIPT_NAME' => '',
        'warden' => warden
      }
    )

    ActionCable.server.broadcast(
      'questions_list',
      ApplicationController.renderer.render(
        partial: 'questions/question',
        locals: {
          question: @question,
          current_user: current_user
        }
      )
    )
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answer.html.slim
- question.answers.each do |answer|
  - if answer.persisted?
    div id = "answer-#{answer.id}"
      p
        = answer.body
      .votes-answer
        div id = "answer_#{answer.id}"
          = render 'votes/vote', resource: answer
      ul
        - if answer.best?
          i.best <- the best answer
        - if user_signed_in?
          - if current_user.author?(answer)
            p
              = link_to 'Mark as best',
                set_best_answer_path(answer),
                method: :patch,
                remote: true,
                class: 'best-answer-link'
            p
              = link_to 'Edit', '', 
                class: 'edit-answer-link', 
                data: { answer_id: answer.id }
            p
              = form_with model: answer, local: false, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
                h5= 'Editing answer'
                p
                  = f.label :body, 'Answer'
                = f.text_area :body, id: "answer_body-#{answer.id}"
                .links
                  = link_to_add_association 'add more files', f, :attachments
                = f.submit 'Save'
            p
              = link_to 'Delete answer', answer_path(answer), method: :delete, remote: true
        - answer.attachments.each do |a|
          div id="attachment_#{a.id}"
            li= link_to a.file.identifier, a.file.url
            p= link_to 'Delete file', delete_attachment_for_answer_question_path(id: answer.id, attachment_id: a.id), method: :delete, remote: true

      b
        = 'Comments'
      .container
        .answer-comments
          - unless answer.comments.empty?
            = render 'comments/comments', commentable: answer, comments: answer.comments
          - else
            .empty-comments-label
              = 'No comments yet'

        - if current_user
            .card.border-primary.mb-3
              .card-body
                .form-group
                  ol
                    = render 'comments/form', commentable: answer, comment: answer.comments.build

app/views/questions/_answers.html.slim
- @question.answers.each do |answer|
  - if answer.persisted?
    div id = "answer-#{answer.id}"
      p
        = answer.body
      div id = "answer_#{answer.id}"
        = render 'votes/vote', resource: answer
      ul
        - if answer.best?
          i.best <- the best answer
        - if user_signed_in?
          - if current_user.author?(answer)
            p
              = link_to 'Mark as best',
                set_best_answer_path(answer),
                method: :patch,
                remote: true,
                class: 'best-answer-link'
            p
              = link_to 'Edit', '', 
                class: 'edit-answer-link', 
                data: { answer_id: answer.id }
            p
              = form_with model: answer, local: false, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
                h5= 'Editing answer'
                p
                  = f.label :body, 'Answer'
                = f.text_area :body, id: "answer_body-#{answer.id}"
                .links
                  = link_to_add_association 'add more files', f, :attachments
                = f.submit 'Save'
            p
              = link_to 'Delete answer', answer_path(answer), method: :delete, remote: true
        - answer.attachments.each do |a|
          div id="attachment_#{a.id}"
            li= link_to a.file.identifier, a.file.url
            p= link_to 'Delete file', delete_attachment_for_answer_question_path(id: answer.id, attachment_id: a.id), method: :delete, remote: true

app/views/questions/_attachment_fields.html.slim
.nested-fields
  .field
    = f.label :file, 'File'
    = f.file_field :file
  = link_to_remove_association "remove file", f

app/views/questions/_edit.html.slim
h2= 'Question'
= @question.body
- if user_signed_in?
  div id="question_#{@question.id}"
    = render 'votes/vote', resource: @question
  - if current_user.author?(@question)
      p= link_to 'Edit question', '', class: 'edit-question-link', data: { question_id: @question.id }
      p
        = form_with model: @question, local: false, class: 'hidden', html: { id: "edit-question-#{@question.id}" } do |f|
          h5= 'Editing question'
          p
            = f.label :body, 'Question'
          = f.text_area :body, id: "question_body-#{@question.id}"
          .links
            = link_to_add_association 'add more files', f, :attachments
          = f.submit 'Save'
      h3= 'Attachments to question'
      ul
        - @question.attachments.each do |a|
          div id="attachment_#{a.id}"
            li= link_to a.file.identifier, a.file.url
            p= link_to 'Delete file', delete_attachment_question_path(id: @question.id, attach_id: a.id), method: :delete, remote: true
  h5.text-center
    b
      = 'Comments'
  .container
    .question-comments
      - unless @question.comments.empty?
        = render 'comments/comments', commentable: @question, comments: @question.comments
      - else
        .empty-comments-label
          = 'No comments yet'

  - if current_user
    .card.border-primary.mb-3
      .card-body
        .form-group
          ol
            = render 'comments/form', commentable: @question, comment: @question.comments.build

app/views/questions/_question.html.slim
table
  thead
    tr
      th Title
      th Body
  tbody
    tr
      td
        = question.title 
      td
        = question.body
      td
        = link_to 'Show', question_path(question)
      td
        = link_to 'Delete', question_path(question), method: :delete, data: { confirm: 'Are you sure?' }
      p
      - if user_signed_in?
        - if question.has_subscribed?(current_user)
          = link_to 'Unsubscribe', unsubscribe_question_path(question), method: :post
        - else
          = link_to 'Subscribe', subscribe_question_path(question), method: :post

app/views/questions/delete_attachments.js.erb
<% if @attachment.destroyed? %>
  $("#attachment_<%= @attachment.id %>").remove()
<% end %>

app/views/questions/index.html.slim
p= 'SEARCH'

p
  = render partial: 'search/form'

- if user_signed_in?
  p= link_to 'Sign out', destroy_user_session_path, method: :delete
- else
  p= link_to 'Sign in', new_user_session_path
  |
  p= link_to 'Create an account', new_user_registration_path

.questions-list
  = render @questions


p= link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
= form_for @question do |f|
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body, 'Text'
    = f.text_area :body
    h4= 'Attachments'
    = f.fields_for :attachments do |a|
    .links
      = link_to_add_association 'add file', f, :attachments

  = f.submit 'Create'

app/views/questions/show.html.slim
.questions
  = render 'edit'
    
h2= 'Answers'

.answers
  = render partial: 'questions/answer', locals: { question: @question }

- if current_user
  = render 'answers/form'

app/views/questions/update.js.erb
<% if @question.errors.present? %>
    <% @question.errors.full_messages.each do |message| %>
        $('.question-errors').html('<%= j message %>');
    <% end %>
<% else %>
    $('.questions').html('<%= j render 'questions/edit' %>');
    $('.edit-question-link').click(function(e) {
        e.preventDefault();
        $(this).hide();
        question_id = $(this).data('questionId');
        $('form#edit-question-' + question_id).show();
    });
<% end %>