config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  concern :voted do
    member do
      patch :vote_up
      patch :vote_down
      delete :revoke_vote
    end
  end

  concern :commented do
    post :comment, on: :member
  end

  resources :questions, concerns: %i[voted commented] do
    resources :answers, concerns: %i[voted commented], shallow: true, except: :index do
      patch :set_best, on: :member
    end
  end

  resources :questions, concerns: :voted do
    post :subscribe, on: :member
    post :unsubscribe, on: :member
    delete :delete_attachment, on: :member
    delete :delete_attachment_for_answer, on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [] do
        get :me, on: :collection
        get :exept_me, on: :collection
      end
      resources :questions do
        resources :answers
      end
    end
  end

  get 'search', to: 'search#search'

  root to: 'questions#index'
  mount ActionCable.server => '/cable'
end

app/models/search.rb
class Search
  SEARCH_OPTIONS = %w(Questions Answers Comments Users)

  def self.filter(query, options = {})
    condition = options[:condition]
    safe_query = Riddle::Query.escape(query)

    if SEARCH_OPTIONS.include?(condition)
      condition.singularize.constantize.search(safe_query)
    else
      ThinkingSphinx.search safe_query
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search
    if params[:query].present?
      @results = Search.filter(params[:query], condition: params[:condition])
    else
      @results = []
    end
    respond_with @results
  end
end

app/views/search/_answer.html.slim
div
  = "Answer of #{answer.user.email}"
  ul
    = truncate(answer.body, length: 200)

app/views/search/_comment.html.slim
div
  = "Comment of #{comment.user.email}"
  ul
    = truncate(comment.body, length: 200)

app/views/search/_form.html.slim
= form_tag search_path, method: 'get', class: 'navbar-form navbar-left'
  .form-group
    = text_field_tag :query, params[:query], class: 'form-control'

  .form-group
    = select_tag(:condition,
        options_for_select(Search::SEARCH_OPTIONS,
        params[:condition]), prompt: 'Everywhere', class: 'form-control')

  = submit_tag 'Search', name: nil, class: 'btn btn-default'

app/views/search/_question.html.slim
div
  = "Question of #{question.user.email}"
  ul
    p= link_to question.title, question_path(question)

app/views/search/_user.html.slim
div = user.email

app/views/search/search.html.slim
h4 Search results

.results
  - if @results.any?
      - @results.each do |result|
        = render partial: "#{result.class.name.downcase}", object: result